In [8]:
from model import *
from data_process import *
from generator import *
from src.training import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Data_loading 

In [4]:
imgs,gd_imgs = load_image_train()
test_image = load_image_test(4)

Loading 90 images
(89, 400, 400, 3)
Loading 90 images
(89, 400, 400, 1)


Train model


In [5]:
in_size = 200

In [9]:
model = unet(input_size = (in_size,in_size,3),pretrained_weights = None)
#model = unet(input_size = (400,400,3),pretrained_weights = None)

In [10]:
image = train_generator(in_size)
#image = train_generator(imgs,gd_imgs,1)

#Callbacks
model_checkpoint = ModelCheckpoint('weights.hdf5',monitor='acc',verbose=1,save_best_only=True)
Learning_reduction = ReduceLROnPlateau(monitor='acc',factor=0.3,patience=10,verbose=1,mode='auto',min_delta=0.0001,cooldown=0,min_lr=0)
Early_Stopping = EarlyStopping(monitor='acc',min_delta=0.0001,patience=10,verbose=1,mode='auto',baseline=None,restore_best_weights=False)
 
model.fit_generator(image,steps_per_epoch=100,epochs=5,callbacks=[Learning_reduction,Early_Stopping,model_checkpoint])

Epoch 1/5
100/100 [==============================] - 186s 2s/step - loss: -134.4503 - acc: 0.3861

Epoch 00001: acc improved from -inf to 0.38613, saving model to weights.hdf5
Epoch 2/5
100/100 [==============================] - 188s 2s/step - loss: -435.8105 - acc: 0.0922

Epoch 00002: acc did not improve from 0.38613
Epoch 3/5
100/100 [==============================] - 186s 2s/step - loss: -568.6638 - acc: 0.0068

Epoch 00003: acc did not improve from 0.38613
Epoch 4/5
100/100 [==============================] - 183s 2s/step - loss: -643.8501 - acc: 0.0053

Epoch 00004: acc did not improve from 0.38613
Epoch 5/5
 35/100 [=========>....................] - ETA: 1:57 - loss: -679.7217 - acc: 0.0049

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/Clara/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-c8196ff3ec42>", line 9, in <module>
    model.fit_generator(image,steps_per_epoch=100,epochs=5,callbacks=[Learning_reduction,Early_Stopping,model_checkpoint])
  File "/Users/Clara/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/Clara/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/Clara/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/Users/Clara/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/User

KeyboardInterrupt: 

Save results of predictions

In [25]:
#print(next(test_image))
#prediction = prediction_generator(next(test_image))


[[[[0.2        0.18039216 0.16862746]
   [0.18431373 0.16862746 0.15686275]
   [0.23137255 0.2        0.18431373]
   ...
   [0.4745098  0.45882353 0.43137255]
   [0.5647059  0.54901963 0.5137255 ]
   [0.5411765  0.5294118  0.49411765]]

  [[0.22352941 0.2        0.18431373]
   [0.19607843 0.1764706  0.16470589]
   [0.21960784 0.19215687 0.1764706 ]
   ...
   [0.28235295 0.27058825 0.25490198]
   [0.5568628  0.5372549  0.5019608 ]
   [0.54901963 0.53333336 0.49803922]]

  [[0.23137255 0.21568628 0.2       ]
   [0.22352941 0.19607843 0.18039216]
   [0.21176471 0.18431373 0.17254902]
   ...
   [0.5411765  0.52156866 0.4862745 ]
   [0.5294118  0.5058824  0.4627451 ]
   [0.5254902  0.5019608  0.45882353]]

  ...

  [[0.5176471  0.49411765 0.44705883]
   [0.54509807 0.5254902  0.48235294]
   [0.54901963 0.5254902  0.48235294]
   ...
   [0.30980393 0.3254902  0.3019608 ]
   [0.3137255  0.32156864 0.3019608 ]
   [0.32941177 0.34117648 0.32156864]]

  [[0.5019608  0.47843137 0.43137255]
   [0.5

TypeError: list indices must be integers or slices, not tuple

In [ ]:
prediction_patch = model.predict_generator(test_image, 4, verbose = 1)

In [39]:
test = prediction_patch.reshape((4,800,800))
numpy2pillow(test[0]).show()

In [62]:
t = prediction.squeeze()

In [75]:
np.vstack(t).shape
a = t.reshape((1,800,800))
a.shape
numpy2pillow(a).show()

TypeError: Cannot handle this data type

In [60]:
prediction = prediction_generator(prediction_patch)

#save_results('save_predictions', prediction)